export enum UserRole {
  CLIENT = 'CLIENT',
  ACCOUNTANT = 'ACCOUNTANT',
  BANK_CLIENT = 'BANK_CLIENT',
  SUPERVISOR = 'SUPERVISOR',
  ADMIN = 'ADMIN',
  DIRECTOR = 'DIRECTOR',
  OTHER_INTERNAL = 'OTHER_INTERNAL',
}
