
export enum UserRole {
  ADMIN = 'ADMIN',
  SUPERVISOR = 'SUPERVISOR',
  ACCOUNTANT = 'ACCOUNTANT', 
  BANK_CLIENT_SPECIALIST = 'BANK_CLIENT_SPECIALIST',
  CLIENT = 'CLIENT',
  USER = 'USER',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL'
}
